[2024-08-08T08:10:08.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T08:10:08.198+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-08T04:00:00+00:00 [queued]>
[2024-08-08T08:10:08.204+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_11str.update_11str scheduled__2024-08-08T04:00:00+00:00 [queued]>
[2024-08-08T08:10:08.205+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 5
[2024-08-08T08:10:08.216+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_11str> on 2024-08-08 04:00:00+00:00
[2024-08-08T08:10:08.225+0000] {standard_task_runner.py:63} INFO - Started process 608 to run task
[2024-08-08T08:10:08.229+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_11str', 'update_11str', 'scheduled__2024-08-08T04:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/str11_batch.py', '--cfg-path', '/tmp/tmpssgwlhv2']
[2024-08-08T08:10:08.231+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask update_11str
[2024-08-08T08:10:08.272+0000] {task_command.py:426} INFO - Running <TaskInstance: update_11str.update_11str scheduled__2024-08-08T04:00:00+00:00 [running]> on host b4c0c56d2c27
[2024-08-08T08:10:08.339+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zzioni' AIRFLOW_CTX_DAG_ID='update_11str' AIRFLOW_CTX_TASK_ID='update_11str' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-08T04:00:00+00:00'
[2024-08-08T08:10:08.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T08:10:08.996+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-08-08T08:10:09.020+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T08:10:09.102+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2024-08-08T08:10:09.168+0000] {logger.py:11} INFO - Driver downloading response is 200
[2024-08-08T08:10:09.263+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T08:10:09.506+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-08-08T08:10:09.565+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2024-08-08T08:10:09.567+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T08:10:09.568+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/str11_batch.py", line 28, in update_11str
    price, prices_id, deleted = extract_price_11str()
  File "/opt/airflow/dags/utils/crawl_11str.py", line 103, in extract_price_11str
    driver = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
TypeError: WebDriver.__init__() got multiple values for argument 'options'
[2024-08-08T08:10:09.577+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=update_11str, task_id=update_11str, execution_date=20240808T040000, start_date=20240808T081008, end_date=20240808T081009
[2024-08-08T08:10:09.588+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task update_11str (WebDriver.__init__() got multiple values for argument 'options'; 608)
[2024-08-08T08:10:09.602+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-08T08:10:09.630+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T08:10:09.633+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
