[2024-08-08T05:11:49.537+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T05:11:49.558+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_coupang.update_coupang scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-08T05:11:49.564+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_coupang.update_coupang scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-08T05:11:49.565+0000] {taskinstance.py:2303} INFO - Starting attempt 7 of 7
[2024-08-08T05:11:49.575+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_coupang> on 2024-08-08 00:00:00+00:00
[2024-08-08T05:11:49.584+0000] {standard_task_runner.py:63} INFO - Started process 2445 to run task
[2024-08-08T05:11:49.587+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_coupang', 'update_coupang', 'scheduled__2024-08-08T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/coupang_batch.py', '--cfg-path', '/tmp/tmpeogtwgqx']
[2024-08-08T05:11:49.588+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask update_coupang
[2024-08-08T05:11:49.631+0000] {task_command.py:426} INFO - Running <TaskInstance: update_coupang.update_coupang scheduled__2024-08-08T00:00:00+00:00 [running]> on host af5f4ca33584
[2024-08-08T05:11:49.704+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zzioni' AIRFLOW_CTX_DAG_ID='update_coupang' AIRFLOW_CTX_TASK_ID='update_coupang' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-08T00:00:00+00:00'
[2024-08-08T05:11:49.705+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T05:11:50.875+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/370 [00:00<?, ?it/s]
[2024-08-08T05:11:50.878+0000] {logging_mixin.py:188} WARNING - 100%|##########| 370/370 [00:00<00:00, 175157.16it/s]
[2024-08-08T05:11:50.879+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T05:11:50.879+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coupang_batch.py", line 229, in coupang_info_manual
    res = pd.DataFrame(columns = ["price_id",
NameError: name 'pd' is not defined
[2024-08-08T05:11:50.892+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=update_coupang, task_id=update_coupang, execution_date=20240808T000000, start_date=20240808T051149, end_date=20240808T051150
[2024-08-08T05:11:50.914+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task update_coupang (name 'pd' is not defined; 2445)
[2024-08-08T05:11:50.960+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-08T05:11:51.011+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T05:11:51.018+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
